YouTube|title|YouTube - Helium|120
Minecraft|title|Minecraft* Forge 1.20.1|120
PrismLauncher|class|PrismLauncher|120
Subnautica|title|Subnautica|30
Elden Ring|title|ELDEN RING|30
Browser|class|Helium|240
