# Confused?
# Check out the WIKI on configuration: https://github.com/mov-cli/mov-cli/wiki/Configuration
[mov-cli]
version = 1
debug = false
player = "mpv"
quality = "auto"
skip_update_checker = false
auto_try_next_scraper = false
hide_ip = true
[mov-cli.ui]
preview = true
watch_options = true
display_quality = false
[mov-cli.plugins]
consumet = "consumet-mc"

[mov-cli.scrapers]
default = "consumet.flixhq"
[mov-cli.http]
timeout = 15
