inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

opacity-rule = [
  "100:name = 'CamPreview'",

  "100:class_g = 'st-256color'",
  "100:class_g = 'st'",
  "100:class_g = 'kitty'",
  "100:class_g = 'neovim'",
  "100:class_g = 'onlyoffice-desktopeditors'",
  "100:class_g = 'vlc'",
  "100:class_g = 'yazi'",
  "100:class_g = 'dwmblocks'",
  "100:class_g = 'dwm'",
  "100:name = 'ONLYOFFICE'",
];
