# BLURRING
# methods: none, gaussian, box, kernel (define custom kernel), dual_kawase
blur:
{
  method = "dual_kawase";
  size = 10;
  strength = 2;
};

# semi-transparent
blur-background = true

# blur-background-frame = true
# Use fixed blur strength rather than adjusting according to window opacity.
blur-background-fixed = true

# set custom blur kernel (method to kernel), preset examples:
# blur-kern = "3x3box";
# blur-kern = "5x5gaussian";


# SHADOWS
#  shadow = true; # this allows me to toggle on shadows solely for qutebrowser, to create a muted/blurred look behind tabs when combined with qutebrowser's transparent tabs setting.
shadow-radius = 0.8; # blur radius
shadow-opacity = 0.6

shadow-offset-x = 0;
shadow-offset-y = 0;

# shadow-color = "#000000"
shadow-color = "#393943" # this could be set with a pywal template instead
# shadow-exclude = [];


# FADING
fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3
backend = "egl";

dithered-present = false;
vsync = true;

detect-rounded-corners = false
detect-client-opacity = true;
use-ewmh-active-win = true
detect-transient = true;
# glx-no-stencil = true
use-damage = true;
log-level = "warn";


# WINDDOW RULES
rules = (
	{ match = "name = 'dwm'"; opacity = 1; },
	{ match = "focused"; opacity = 0.75; },
	{ match = "!focused"; opacity = 0.75; },
	{ match = "tooltip"; fade = true; shadow = true; opacity = 0.5; focus = true; full-shadow = false; },
	{ match = "popup_menu"; opacity = 0.7; },
	{ match = "dropdown_menu"; opacity = 0.7; },
    # Exceptions: always fully opaque when focused 
  { match = "class_g = 'discord'"; opacity = 1.0; },
  { match = "class_g = 'org.gnome.Nautilus'"; opacity = 1.0; },
  { match = "class_g *?= 'helium'"; opacity = 1.0; },
  { match = "class_g = 'CurseForge'"; opacity = 1.0; },
  { match = "class_g = 'Minecraft' || class_g = 'minecraft'"; opacity = 1.0; },
  { match = "name *= 'Minecraft Forge'"; opacity = 1.0; }
);
